blueprints/posts/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])

blueprints/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)

from blueprints.posts import routes

blueprints/posts/routes.py
from flask import request, render_template, abort, flash, redirect, url_for, g

from blueprints import flash_form_errors
from blueprints.posts import bp
from blueprints.posts.forms import PostForm
from persistence.repository.post import PostRepository
from persistence.model.post import Post
from security.decorators import is_admin, is_fully_authenticated


@bp.route('/')
@is_fully_authenticated
def list_all():
    if request.args.get('search'):
        query_string = request.args.get('query_string')

        if request.args.get("ascending"):
            ascending = True
        else:
            ascending = False

        posts = PostRepository.filter(query_string, ascending)
    else:
        posts = PostRepository.find_all()

    return render_template('posts/list.html', posts=posts)


@bp.route('/view/<int:post_id>')
@is_fully_authenticated
def view(post_id):
    post = PostRepository.find_by_id(post_id) or abort(404)

    return render_template('posts/view.html', post=post)


@bp.route('/create', methods=('GET', 'POST'))
@is_fully_authenticated
@is_admin
def create():
    form = PostForm()
    if form.validate_on_submit():
        post = Post()
        post.form_update(form)
        post.author_id = g.user.id
        post.save()
        flash('Post added', 'success')

        return redirect(url_for('posts.edit', post_id=post.id))
    if form.errors:
        flash_form_errors(form)

    return render_template('posts/form.html', form=form, create=True)


@bp.route('/edit/<int:post_id>', methods=('GET', 'POST'))
@is_fully_authenticated
@is_admin
def edit(post_id):
    post = PostRepository.find_by_id(post_id) or abort(404)
    form = PostForm(obj=post)

    if form.validate_on_submit():
        post.form_update(form)
        post.save()
        flash("Poszt editet", 'success')
        return redirect(url_for('posts.edit', post_id=post.id))
    if form.errors:
        flash_form_errors(form)

    return render_template('posts/form.html', form=form, post=post)


@bp.route('/delete/<int:post_id>', methods=('POST',))
@is_fully_authenticated
@is_admin
def delete(post_id):
    post = PostRepository.find_by_id(post_id) or abort(404)

    post.delete()
    flash('Post deleted.', 'success')

    return redirect(url_for('posts.list_all'))

templates/posts/form.html
{% extends "base.html" %}

{% block title %}
{% if create %}
    Create
{% else %}
    Edit
{% endif %}
{% endblock %}

{% block head %}
{% endblock %}

{% block main %}
    <a href="{{ url_for('posts.list_all') }}" class="btn btn-dark me-4 my-2" onclick="return confirmChanges()"><i class="fa fa-arrow-left"></i> Back to posts</a>

    <form method="post" onchange="changed = true;" id="form">
    {{ form.csrf_token() }}
    <div class="form-group mb-1">
        {{ form.content.label }}
        {{ form.content(class="form-control no-resize", id='content')}}
    </div>
</form>

<div class="d-flex align-items-center">
        <button type="submit" onclick="document.getElementById('form').submit()" class="btn btn-primary-dark">
            <i class="fa-solid fa-floppy-disk"></i> Save
        </button>

        {% if not create %}
            <form action="{{ url_for('posts.delete', post_id=post.id) }}" method="post"
                  onsubmit='return confirm("Are you sure you wish to delete the post?")' class="d-inline">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-dark mx-2">
                    <i class="fa-solid fa-trash-can"></i> Delete
                </button>
            </form>
        {% endif %}
</div>

<script>
    let changed = false;
    function confirmChanges(){
        if (changed === true){
            return confirm("Are you sure you wish to leave? You have unsaved changes.");
        }
        return true;
    }
</script>

{% endblock %}

templates/posts/list.html
{% extends "base.html" %}

{% block title %}Posts{% endblock %}

{% block before_main %}
    <button type="button" class="btn btn-dark btn-floating btn-lg" id="scrollToTopButton" onclick="backToTop()">
      <i class="fas fa-arrow-up"></i>
    </button>
{% endblock %}

{% block main %}
<div class="d-flex align-items-center my-2">
    {% if is_admin() %}
        <a href="{{ url_for('posts.create') }}" class="btn btn-dark me-2">
            <i class="fa-solid fa-plus-circle"></i> Create post
        </a>
    {% endif %}
</div>
<div id="searchPostFormDiv">
    <form id="searchPostForm" method="get">
        <input type="hidden" name="search" value="_">
        <div class="form-group mb-3">
            <label for="query_string">Phrase</label>
            <input type="text" name="query_string" id="query_string" class="form-control">
        </div>
        <div class="form-group">
            <label for="ascending" class="checkbox-label">Ascending?</label>
            <input type="checkbox" name="ascending" id="ascending">
        </div>
        <div class="d-flex align-items-center mb-3">
            <button type="submit" class="btn btn-primary-dark me-2"><i class="fa-solid fa-search"></i> Search</button>
            <a href="{{ url_for('posts.list_all') }}" class="btn btn-dark me-2">
                <i class="fa-solid fa-rotate-left"></i> Reset</a>
        </div>
    </form>
</div>

<div id="content">
    {% for post in posts %}
        {% include "posts/post.html" %}
    {% endfor %}
</div>

{% endblock %}

{% block after_main %}

{% endblock %}

templates/posts/post.html
<div class="post">
    <div class="small-text gray-text">
        Author: {{ post.author.name }}
    </div>

    <div class="d-flex" style="font-size: 0.95rem">
        {% if is_admin() %}
            {% if not request.endpoint == 'posts.view' %}
                <a href="{{ url_for('posts.view', post_id=post.id) }}" class="btn btn-secondary me-1"><i class="fa-regular fa-eye"></i> View</a>
            {% endif %}

            <a href="{{ url_for('posts.edit', post_id=post.id) }}" class="btn btn-dark me-1"><i class="fas fa-edit"></i> Edit</a>
            <form action="{{ url_for('posts.delete', post_id=post.id) }}" method="post"
                  onsubmit='return confirm("Are you sure you wish to delete the post?")'>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-primary-dark"><i class="fas fa-trash"></i> Delete</button>
            </form>
        {% endif %}
    </div>

    <hr class="mb-3">
    <div class="text-break lh-base" style="font-size: 1.1em; letter-spacing: 1px"> {{ post.content | safe_br }} </div>
</div>

templates/posts/view.html
{% extends "base.html" %}

{% block title %}Post{% endblock %}

{% block main %}

<a href="{{ url_for('posts.list_all') }}" class="btn btn-dark me-4 my-2" onclick="return confirmChanges()"><i class="fa fa-arrow-left"></i> Back to posts</a>

{% include "posts/post.html" %}

{% endblock %}