blueprints/users/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import SubmitField, StringField, PasswordField, HiddenField
from wtforms.fields.choices import SelectField
from wtforms.validators import DataRequired, length, EqualTo
from persistence.model.user import roles


class RegisterUserForm(FlaskForm):
    name = StringField('Username', validators=[DataRequired(), length(max=32)])
    password = PasswordField('Password', validators=[DataRequired(), length(max=32, min=4)])
    password_again = PasswordField('Password again', validators=[DataRequired(), length(max=32, min=4), EqualTo('password')])


class EditUserRoleForm(FlaskForm):
    role = SelectField('Role', choices=[(role, roles[role]) for role in roles.keys() if role != 'super_admin'], validators=[DataRequired()])
    user_id = HiddenField('user_id', validators=[DataRequired()])

    def set_role(self, role_name):
        self.role.data = role_name

    def set_user_id(self, user_id):
        self.user_id.data = user_id


class UserSettingsForm(FlaskForm):
    name = StringField('Username', validators=[DataRequired(), length(max=32)])


class UserPasswordResetForm(FlaskForm):
    old_password = PasswordField('Old password', validators=[DataRequired()])
    new_password = PasswordField('New password', validators=[DataRequired(), length(max=32, min=4)])
    new_password_again = PasswordField('New password again', validators=[DataRequired(), length(max=32, min=4),
                                                                     EqualTo('new_password')])


class DeleteUserForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), length(max=32, min=4)])

blueprints/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from blueprints.users import routes

blueprints/users/routes.py
from flask import g, redirect, url_for, flash, render_template, abort
from security.decorators import is_admin, is_fully_authenticated
from blueprints.users import bp
from blueprints.pages import bp as base_bp
from blueprints.users.forms import RegisterUserForm, EditUserRoleForm, UserSettingsForm, UserPasswordResetForm, DeleteUserForm
from persistence.repository.user import UserRepository
from persistence.model.user import User


@bp.route('/', methods=['GET', 'POST'])
@is_fully_authenticated
@is_admin
def list_all():
    users = UserRepository.find_all()
    role_form = EditUserRoleForm()

    if role_form.validate_on_submit():
        user = UserRepository.find_by_id(role_form.user_id.data) or abort(404)
        if user.is_super_admin or g.user.id == user.id:
            abort(403)

        user.role = role_form.role.data
        user.save()
        flash(f"The role of {user.name} was successfully changed to {user.role_display}", 'success')
        return redirect(url_for('users.list_all'))

    return render_template("users/list.html", users=users, role_form=role_form)


@bp.route('/delete/<int:user_id>', methods=['POST'])
@is_fully_authenticated
@is_admin
def delete(user_id):
    user = UserRepository.find_by_id(user_id) or abort(404)
    if user.is_super_admin or g.user.id == user.id:
        abort(403)

    username = user.name
    user.delete()
    flash(f"The account of {username} was successfully deleted", 'success')
    return redirect(url_for('users.list_all'))


@base_bp.route('/register', methods=['GET', 'POST'])
def register():
    if g.user is not None:
        return redirect(url_for('pages.home'))

    form = RegisterUserForm()
    user = User()
    if form.validate_on_submit():
        if UserRepository.find_by_name(form.name.data.strip()):
            flash('The username is already in use', 'error')
            return redirect(url_for('pages.register'))
        user.form_update(form)
        user.role = 'user'
        user.save()
        flash("Registration successful", 'success')

        return redirect(url_for('security.login'))

    return render_template('users/register.html', form=form)


@base_bp.route('/settings')
@is_fully_authenticated
def settings():
    user_settings_form = UserSettingsForm()
    user_password_form = UserPasswordResetForm()
    user_delete_form = DeleteUserForm()

    user_settings_form.name.data = g.user.name

    return render_template('users/settings.html', user_settings_form=user_settings_form, user_password_form=user_password_form, user_delete_form=user_delete_form)


@bp.route('/user-settings', methods=['POST'])
@is_fully_authenticated
def user_settings():
    user = g.user
    user_settings_form = UserSettingsForm()

    if user_settings_form.validate_on_submit():
        if UserRepository.find_by_name(user_settings_form.name.data.strip()):
            flash('The username is already in use', 'error')
            return redirect(url_for('pages.settings'))

        user.name = user_settings_form.name.data
        user.save()

        flash("The username was successfully changed", 'success')

    return redirect(url_for('pages.settings'))


@bp.route('/password_reset', methods=['POST'])
@is_fully_authenticated
def password_reset():
    user = g.user
    user_password_form = UserPasswordResetForm()

    if user_password_form.validate_on_submit():
        if user.check_password(user_password_form.old_password.data):
            user.password = user_password_form.new_password.data
            user.save()
            flash("The password was changed successfully", 'success')
        else:
            flash("The old password is incorrect", 'error')

    return redirect(url_for('pages.settings'))


@is_fully_authenticated
@bp.route('/delete-self', methods=['POST'])
def delete_self():
    user = g.user
    user_delete_form = DeleteUserForm()

    if user.is_super_admin:
        abort(403)

    if user_delete_form.validate_on_submit():
        if not user.check_password(user_delete_form.password.data):
            flash("Incorrect password", 'error')
            return redirect(url_for('pages.settings'))
        user.delete()
        flash("The account was deleted successfully", 'success')

    return redirect(url_for('security.login'))

templates/users/list.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}

{% block head %}
{% endblock %}

{% block before_main %}
    <button type="button" class="btn btn-dark btn-floating btn-lg" id="scrollToTopButton" onclick="backToTop()">
      <i class="fas fa-arrow-up"></i>
    </button>
{% endblock %}

{% block main %}
{% for user in users %}
    {% if not (user.is_super_admin or user.id == g.user.id) %}
        <div class="user p-4 my-3">
            <h5 class="user-name">{{ user.name }}</h5>
            {% do role_form.set_role(user.role) %}
            {% do role_form.set_user_id(user.id) %}

            <form method="post" onsubmit="return confirm('Are you sure you wish to change the role of {{ user.name }}?')">
                {{ role_form.csrf_token() }}
                {{ role_form.role(class="form-control") }}
                {{ role_form.user_id() }}
                <div style="float: left">
                    <button type="submit" class=" btn btn-primary-dark mt-3">
                        <i class="fa-solid fa-floppy-disk"></i> Save
                    </button>
                </div>
            </form>

            <form action="{{ url_for('users.delete', user_id=user.id) }}" method="post"
                  onsubmit='return confirm("Are you sure you wish to delete {{ user.name }}?")' class="d-inline">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                     <button id="torles"  type="submit" class=" btn btn-secondary mx-2 mt-3">
                        <i class="fas fa-trash"></i> Delete
                    </button>
            </form>

        </div>
    {% endif %}
{% endfor %}
{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block heading %}
    {% with heading_content="Register" %}
        {% include "heading.html" %}
    {% endwith %}
{% endblock %}

{% block main %}
    <form method="post" class="form">
        {{ form.csrf_token() }}

        <div class="form-group mb-1">
            {{ form.name.label }}
            {{ form.name(class="form-control") }}
        </div>
         <div class="form-group mb-1">
                <label for="password">{{ form.password.label }}</label>
                <div class="input-group">
                    {{ form.password(class="form-control", id="password", onkeyup="validatePassword()") }}
                    <span class="show-password-btn ms-4 mt-1" style="font-size: 1.2em" onclick="togglePasswordVisibility('password', this); togglePasswordVisibility('password_again', this)">
                        <i class="fa fa-eye"></i>
                    </span>
                </div>
            </div>
            <div class="form-group mb-1">
                <label for="password_again">{{ form.password_again.label }}</label>
                {{ form.password_again(class="form-control", id="password_again", onkeyup="validatePassword()") }}
            </div>
            <div class="match" id="passwordMatchMessage"></div>

        <div class="form-group">
            <button type="submit" class="btn btn-dark" id="submit"><i class="fa-solid fa-floppy-disk"></i> Register</button>
        </div>
    </form>
{% endblock %}

templates/users/settings.html
{% extends "base.html" %}

{% block title %}Settings{% endblock %}

{% block head %}

{% endblock %}

{% block heading %}
    {% with heading_content="User settings" %}
        {% include "heading.html" %}
    {% endwith %}
{% endblock %}

{% block main %}
    <h5 class="gray-text"><u>Change username</u></h5>
    <form method="post" action="{{ url_for('users.user_settings') }}">
        {{ user_settings_form.csrf_token(id=False) }}

        <div class="form-group">
            {{ user_settings_form.name.label }}
            {{ user_settings_form.name(class="form-control") }}
        </div>

        <div class="form-group mb-4">
            <button type="submit" class="btn btn-dark"><i class="fa-solid fa-floppy-disk"></i> Save</button>
        </div>
    </form>

    <h5 class="gray-text"><u>Change password</u></h5>
    <form method="post" action="{{ url_for('users.password_reset') }}">
        {{ user_password_form.csrf_token(id=False) }}
        <div class="form-group mb-1">
            {{ user_password_form.old_password.label }}
            <div class="input-group">
                {{ user_password_form.old_password(class="form-control", id="old_password") }}
                <span class="show-password-btn ms-4 mt-1" style="font-size: 1.2em" onclick="togglePasswordVisibility('old_password', this);">
                    <i class="fa fa-eye"></i>
                </span>
            </div>

            {{ user_password_form.new_password.label }}
                <div class="input-group">
                    {{ user_password_form.new_password(class="form-control", id="password", onkeyup="validatePassword()") }}
                    <span class="show-password-btn ms-4 mt-1" style="font-size: 1.2em" onclick="togglePasswordVisibility('password', this); togglePasswordVisibility('password_again', this)">
                        <i class="fa fa-eye"></i>
                    </span>
                </div>
            </div>
            <div class="form-group">
                {{ user_password_form.new_password_again.label }}
                {{ user_password_form.new_password_again(class="form-control", id="password_again", onkeyup="validatePassword()") }}
            </div>
            <div class="match" id="passwordMatchMessage"></div>

        <div class="form-group mb-4">
            <button type="submit" disabled class="btn btn-dark" id="submit"><i class="fa-solid fa-floppy-disk"></i> Save</button>
        </div>
    </form>

    {% if not g.user.is_super_admin %}
        <h5 class="gray-text"><u>Delete account</u></h5>
        <form method="post" action="{{ url_for('users.delete_self') }}" onsubmit="return confirm('Are you sure you wish to delete your account?')">
        {{ user_delete_form.csrf_token(id=False) }}
        {{ user_delete_form.password.label }}
        <div class="form-group">
            {{ user_delete_form.password(class="form-control", id=False) }}
        </div>
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> Delete account</button>
        </form>
    {% endif %}

{% endblock %}